DUT      = sdm_cic3_tb
TOPLEVEL = $(DUT)
MODULE   = test_$(DUT)
VERILOG_SOURCES += $(TB_DIR)/$(DUT).sv
VERILOG_SOURCES += $(SRC_DIR)/cic3.sv
VERILOG_SOURCES += $(SRC_DIR)/sine_wave.sv
VERILOG_SOURCES += $(SRC_DIR)/sdm_rnm.sv

include ../cocotb_inc.mk